version: '3'

services:

  vidalia:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    volumes:
      - .:/go/src/vidalia
    environment:
      - VIDALIA_PATH=/go/src/vidalia/test/hierarchy
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672
    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbit
    volumes:
      - /var/lib/fanuniverse/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
